### ISSUE TITLE
"Politeness" support

### ISSUE THREAD

**Issue by alek** [Supplyframe/grunf#26]
We need to add support for limiting number of concurrent requests to a single hosts

(http://en.wikipedia.org/wiki/Web_crawler#Politeness_policy)

That is - if more than X concurrent queries are to be dispatched to given host - query X+1 should wait until at least one of initial X requests have returned response

**Comment by dryman** [comment]
Don't send init requests all at once.
For host X, don't send more than 5 (or other) at one time

**Comment by dryman** [comment]
Only have basic support: send initial requests with 1 sec interval.
