### ISSUE TITLE
Simple Content Validation DSL

### ISSUE THREAD

**Issue by alek** [Supplyframe/grunf#4]
We should be able to pass a simple logic in configuration, dealing with validation of retrieved content 

example use case :
- poll http://www.yahoo.com every 1000ms
- measure response time
- validate that response contains "</html>" and payload is greater than 200k but less than 400k
- if validation fails -> emit "ERROR" event

**Comment by dryman** [comment]
Done
See conf.example.clj

Redirect is not implemented yet.

``` clj
[{:name "yahoo"
  :url "http://www.yahoo.com/"
  :meta {:from "0.0.0.0"}
  :interval 1000
  :validator #(re-find #"yahoo" %)
  :http-options {:timeout 2000
                 :user-agent "Mozilla"}
  :redirect True
  }]
```
