### ISSUE TITLE
rc script 

### ISSUE THREAD

**Issue by alek** [Supplyframe/grunf#5]
We need to create a simple rc script (rcGrunf.sh) that enables the process to run in the background. It should suport following params:
- start : starts the service daemon
- stop : stops the service daemon
- restart : restarts the service
- reload-config : reloads configuration
- status : reports service status

**Comment by dryman** [comment]
Can also check
https://github.com/arohner/lein-daemon

**Comment by dryman** [comment]
We should use drip, and find out if we can use the drip_daemon backend
https://github.com/flatland/drip
