### ISSUE TITLE
Remote Configuration / Dynamic Reload Support

### ISSUE THREAD

**Issue by alek** [Supplyframe/grunf#8]
We need to be able to pass configuration node as parameter when starting the node (example --config-host http://foo.bar.com/grunf/host_config/hostname.clj)

Service should periodically poll this endpoint at defined interval & reload configuration when changed change.

**Comment by dryman** [comment]
Since the config file will be evaluated in service, I have concern about security issues.
Imagine if someone hacked into the config host and rewrite the config.clj, or highjacked the query and insert the code he want to evaluate. We can discuss more on this.

**Comment by dryman** [comment]
Need to spend some time to understand how to integrate with puppet
